from tkinter import *
class GUI:
    def __init__(self, master):
     frame = Frame(master)
     frame.pack()
     frame.configure(background='white')
     self.button1 = Button(frame, bg="white")
     self.button1.config(image=photo1)
     self.button2 = Button(frame,bg="white")
     self.button2.config(image=photo2)
     self.button3 = Button(frame,bg="white")
     self.button3.config(image=photo3)
     self.button4 = Button(frame,bg="white")
     self.button4.config(image=photo4)
     self.button5 = Button(frame,bg="white")
     self.button5.config(image=photo5)
     self.button6 = Button(frame,bg="white")
     self.button6.config(image=photo6)
     self.button7 = Button(frame, bg="white")
     self.button7.config(image=photo7)
     self.button8 = Button(frame, bg="white")
     self.button8.config(image=photo8)
     self.button9 = Button(frame, bg="white")
     self.button9.config(image=photo9)
     self.back = Button(frame, bg="white")
     self.back.config(image=photoB)
     self.quitButton = Button(frame, command=frame.quit, bg="white")
     self.quitButton.config(image=photoE)
     self.back.grid(row=0, column=0)
     self.button1.grid(row=0,column=1)
     self.button2.grid(row=0, column=2)
     self.button3.grid(row=0, column=3)
     self.quitButton.grid(row=0, column=4)
     self.button4.grid(row=1, column=1)
     self.button5.grid(row=1, column=2)
     self.button6.grid(row=1, column=3)
     self.button7.grid(row=2, column=1)
     self.button8.grid(row=2, column=2)
     self.button9.grid(row=2, column=3)

root= Tk()
photo1 = PhotoImage(file="Reminders.png")
photo2 = PhotoImage(file="Calendar.png")
photo3 = PhotoImage(file="News.png")
photo4 = PhotoImage(file="Quran.png")
photo5 = PhotoImage(file="Music1.png")
photo6 = PhotoImage(file="Audiobook.png")
photo7 = PhotoImage(file="Exercise.png")
photo8 = PhotoImage(file="Games.png")
photo9 = PhotoImage(file="Weather.png")
photoB = PhotoImage(file="Back.png")
photoE = PhotoImage(file="Exit.png")
b= GUI(root)
root.title("Intelligent Fellow")
root.configure(background='white')
root.mainloop()