from tkinter import *
class GUI:
    def __init__(self, master):
     frame = Frame(master)
     frame.pack()
     frame.configure(background='white')
     self.label_1 = Label(frame, text="Username", bg="white", font=("Helvetica", 14))
     self.label_2 = Label(frame, text="Password", bg="white", font=("Helvetica", 14))
     self.entry_1 = Entry(frame)
     self.entry_2 = Entry(frame)
     self.label_1.grid(row=0, sticky=E)
     self.label_2.grid(row=1, sticky=E)
     self.entry_1.grid(row=0, column=1)
     self.entry_2.grid(row=1, column=1)
     self.button = Button(frame, text="  Login  ", bg="white", fg="black", font=("Helvetica", 14))
     self.button.grid(row=2)
     self.back = Button(frame, bg="white")
     self.back.config(image=photoB)
     self.back.grid(row=2, column=1)
root= Tk()
photo = PhotoImage(file="Home.png")
photoB = PhotoImage(file="Back.png")
label = Label(root, image=photo)
label.pack()
b= GUI(root)
root.title("Intelligent Fellow")
root.configure(background='white')
root.mainloop()