from tkinter import *
class GUI:
    def __init__(self, master):
     frame = Frame(master)
     frame.pack()
     frame.configure(background='white')
     self.button1 = Button(frame, bg="white")
     self.button1.config(image=photo1)
     self.back = Button(frame, bg="white")
     self.back.config(image=photoB)
     self.quitButton = Button(frame, command=frame.quit, bg="white")
     self.quitButton.config(image=photoE)
     self.button1.grid(row=1, column=1)
     self.back.grid(row=2, column=0)
     self.quitButton.grid(row=2,column=1)
root= Tk()
photo = PhotoImage(file="Piano.png")
photo1 = PhotoImage(file="Play.png")
photoB = PhotoImage(file="Back.png")
photoE = PhotoImage(file="Exit.png")
label = Label(root, image=photo)
label.pack()
b= GUI(root)
root.title("Intelligent Fellow")
root.configure(background='white')
root.mainloop()