from tkinter import *

class GUI:
    def __init__(self, master):
     frame = Frame(master)
     frame.pack()
     frame.configure(background='white')
     self.button1 = Button(frame, bg="white")
     self.button1.config(image=photo1)
     #self.button2 = Button(frame,bg="white", command=openArabicSongs)
     #self.button2.config(image=photo2)
     #self.button3 = Button(frame,bg="white", command=openRelaxation)
     #self.button3.config(image=photo3)
     #self.button4 = Button(frame, bg="white", command=openEnglishSongs)
     #self.button4.config(image=photo4)
     self.button1.grid(row=2,column=0)
     #self.button2.grid(row=2, column=1)
     #self.button3.grid(row=2, column=2)
     #self.button4.grid(row=2, column=3)

root= Tk()
#photo = PhotoImage(file="C:/Users/Reemy/Documents/GitHub/std_googleAssistant/GUI/Icons/Home.png")
#label = Label(root,image=photo)
label_1 = Label(root, text="Choose Your Fellow", bg="white", font=("Helvetica", 20))
label_1.pack(side="top", anchor=N)
photoB = PhotoImage(file="/home/pi/std_googleAssistant/GUI/Icons/Back.png")
photoE = PhotoImage(file="/home/pi/std_googleAssistant/GUI/Icons/Exit.png")
back = Button(root, bg="white")
back.config(image=photoB)
quitButton = Button(root, command=root.quit, bg="white")
quitButton.config(image=photoE)
back.pack(side="left",anchor=NW)
quitButton.pack(side="right", anchor=NE)
#label.pack(side="top", anchor=N)
photo1 = PhotoImage(file="/home/pi/std_googleAssistant/GUI/Icons/Robo1.png")
#photo2 = PhotoImage(file="C:/Users/Reemy/Documents/GitHub/std_googleAssistant/GUI/Icons/Emirati.png")
#photo3 = PhotoImage(file="C:/Users/Reemy/Documents/GitHub/std_googleAssistant/GUI/Icons/Relaxation.png")
#photo4 = PhotoImage(file="C:/Users/Reemy/Documents/GitHub/std_googleAssistant/GUI/Icons/English.png")
b= GUI(root)
root.geometry("1000x920")
root.title("Intelligent Fellow")
root.configure(background='white')
root.mainloop()