from tkinter import *
class GUI:
    def __init__(self, master):
     frame = Frame(master)
     frame.pack()
     frame.configure(background='white')
     self.label_1 = Label(frame, text="Username:", bg="white", font=("Agency FB", 18))
     self.label_2 = Label(frame, text="Password:", bg="white", font=("Agency FB", 18))
     self.label_3 = Label(frame, text="Age:", bg="white", font=("Agency FB", 18))
     self.label_4 = Label(frame, text="Gender", bg="white", font=("Agency FB", 18))
     self.label_5 = Label(frame, text="Enter M for male, and F for female", bg="white",fg="red", font=("Agency FB", 16))
     self.entry_1 = Entry(frame)
     self.entry_2 = Entry(frame)
     self.entry_3 = Entry(frame)
     self.entry_4 = Entry(frame)
     self.label_1.grid(row=0, column=0, sticky=E)
     self.label_2.grid(row=1, column=0, sticky=E)
     self.label_3.grid(row=2, column=0, sticky=E)
     self.label_4.grid(row=3, column=0, sticky=E)
     self.label_5.grid(row=4, column=1)
     self.entry_1.grid(row=0, column=1)
     self.entry_2.grid(row=1, column=1)
     self.entry_3.grid(row=2, column=1)
     self.entry_4.grid(row=3, column=1)
root= Tk()
photo = PhotoImage(file="C:/Users/Reemy/Documents/GitHub/std_googleAssistant/GUI/Icons/SignUp.png")
photoN = PhotoImage(file="C:/Users/Reemy/Documents/GitHub/std_googleAssistant/GUI/Icons/Next.png")
photoB = PhotoImage(file="C:/Users/Reemy/Documents/GitHub/std_googleAssistant/GUI/Icons/Back.png")
photoE = PhotoImage(file="C:/Users/Reemy/Documents/GitHub/std_googleAssistant/GUI/Icons/Exit.png")
back = Button(root, bg="white")
back.config(image=photoB)
next = Button(root, bg="white")
next.config(image=photoN)
quitButton = Button(root, command=root.quit, bg="white")
quitButton.config(image=photoE)
back.pack(side="left",anchor=NW)
next.pack(side="bottom", anchor=NE)
quitButton.pack(side="right", anchor=NE)
label = Label(root, image=photo)
label.pack()
b= GUI(root)
root.title("Intelligent Fellow")
root.geometry("1000x920")
root.configure(background='white')
root.mainloop()